name: signature-analyzer-gpu-env
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - anaconda
  - pytorch
  - torchvision
  - cudatoolkit==9.0
  - numpy
  - pandas
  - pyarrow
  - scikit-image
  - scikit-learn
  - scipy
  - snakemake
